[workspace]
resolver = "3"
members = [
    "crates/openxml-xml",
    "crates/openxml-opc",
    "crates/openxml-codegen",
    "crates/openxml-schema",
    "crates/openxml-testkit",
    "crates/openxml-core",
    "crates/openxml-chart",
    "crates/openxml-docx",
    "crates/openxml-xlsx",
    "crates/openxml-pptx",
    "crates/openxml",
    "crates/openxml-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AdonisGM/open-xml-rust"

[workspace.dependencies]
openxml-xml = { path = "crates/openxml-xml" }
openxml-opc = { path = "crates/openxml-opc" }
openxml-schema = { path = "crates/openxml-schema" }
openxml-testkit = { path = "crates/openxml-testkit" }
openxml-core = { path = "crates/openxml-core" }
openxml-chart = { path = "crates/openxml-chart" }
openxml-docx = { path = "crates/openxml-docx" }
openxml-xlsx = { path = "crates/openxml-xlsx" }
openxml-pptx = { path = "crates/openxml-pptx" }
quick-xml = "0.42"
zip = { version = "8.6", default-features = false, features = ["deflate-flate2-zlib-rs"] }
roxmltree = "0.21"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.dev.package."*"]
opt-level = 1
