//! Strongly typed Office Open XML schema types.
//!
//! Every module corresponds to one ECMA-376 Transitional XML Schema file and
//! is generated by `openxml-codegen` — see `crates/openxml-codegen`. Types keep
//! their schema names (`CT_P`, `ST_Jc`, `EG_PContent`) so they can be looked
//! up directly in the specification; documentation comments quote the
//! relevant section of ECMA-376 Part 1.
//!
//! * `CT_*` structs implement [`XmlRead`](openxml_xml::XmlRead) and
//!   [`XmlWrite`](openxml_xml::XmlWrite). Attributes are `Option` fields,
//!   child elements are `Option<Box<_>>` / `Vec<_>` fields in schema order,
//!   and choices are enums.
//! * Content that the schema does not describe is preserved in
//!   `extra_attrs` / `extra_children` (or an enum's `Other` variant), so a
//!   document read and written back loses nothing.
//! * `ST_*` simple types implement [`XmlValue`](openxml_xml::XmlValue).
//! * Each module's `elements` submodule lists the global elements as
//!   [`ElementDef`](openxml_xml::ElementDef) constants, the entry points for
//!   parsing and writing whole parts.
//!
//! ```
//! use openxml_schema::wml;
//!
//! let xml = r#"<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
//!   <w:body><w:p><w:r><w:t>Hello</w:t></w:r></w:p></w:body></w:document>"#;
//! let doc = wml::elements::DOCUMENT.parse(xml)?;
//! let body = doc.body.as_ref().unwrap();
//! assert_eq!(body.block_level_elts.len(), 1);
//! let out = wml::elements::DOCUMENT.to_xml(&doc);
//! assert!(out.contains("<w:t>Hello</w:t>"));
//! # Ok::<(), openxml_xml::Error>(())
//! ```

#![allow(clippy::large_enum_variant)]

mod generated;
mod prelude;

pub use generated::*;
pub use openxml_xml as xml;
