//! Rust source emission for the IR.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::ir::*;
use crate::names::doc_text;

/// Generated source files: `(relative path, contents)`.
pub fn emit_crate(krate: &Crate) -> Vec<(String, String)> {
    let mut files = Vec::new();
    let mut root = String::new();
    root.push_str(
        "// @generated by openxml-codegen from the ECMA-376 Transitional schemas. Do not edit.\n\n",
    );
    for m in &krate.modules {
        let _ = writeln!(root, "pub mod {};", m.name);
    }
    root.push_str(
        "\n/// Parses a document whose root is any global element of the schemas and serializes it again.\n\
         ///\n\
         /// Returns `None` when the root element is not a global element of the schemas. Useful for\n\
         /// validating that parts survive a read/write cycle.\n\
         pub fn round_trip_xml(xml: &str) -> Option<openxml_xml::Result<String>> {\n\
         \x20   use openxml_xml::Ns;\n\
         \x20   let (ns, local) = match openxml_xml::root_name(xml) {\n\
         \x20       Ok(n) => n,\n\
         \x20       Err(e) => return Some(Err(e)),\n\
         \x20   };\n\
         \x20   Some(match (ns, local.as_str()) {\n",
    );
    for m in &krate.modules {
        for g in &m.globals {
            let _ = writeln!(
                root,
                "        (Ns::{}, {:?}) => {{ let d = {}::elements::{}; d.parse(xml).map(|v| d.to_xml(&v)) }}",
                m.ns, g.local, m.name, g.const_name
            );
        }
    }
    root.push_str("        _ => return None,\n    })\n}\n");
    root.push_str(
        "\n/// Whether `(ns, local)` names a global element of the schemas.\n\
         pub fn is_known_root(ns: openxml_xml::Ns, local: &str) -> bool {\n\
         \x20   use openxml_xml::Ns;\n\
         \x20   matches!((ns, local), ",
    );
    let pats: Vec<String> = krate
        .modules
        .iter()
        .flat_map(|m| {
            m.globals
                .iter()
                .map(move |g| format!("(Ns::{}, {:?})", m.ns, g.local))
        })
        .collect();
    root.push_str(&if pats.is_empty() {
        "(_, _) if false".to_owned()
    } else {
        pats.join(" | ")
    });
    root.push_str(")\n}\n");
    root.push_str("\n/// Every global element of the schemas as `(namespace, local name)`.\n");
    let _ = writeln!(root, "pub const GLOBAL_ELEMENTS: &[(openxml_xml::Ns, &str)] = &[");
    for m in &krate.modules {
        for g in &m.globals {
            let _ = writeln!(root, "    (openxml_xml::Ns::{}, {:?}),", m.ns, g.local);
        }
    }
    root.push_str("];\n");
    files.push(("mod.rs".to_owned(), root));
    for m in &krate.modules {
        files.push((format!("{}.rs", m.name), emit_module(m)));
    }
    files
}

struct Out {
    buf: String,
    module: String,
}

impl Out {
    fn line(&mut self, s: &str) {
        self.buf.push_str(s);
        self.buf.push('\n');
    }

    fn doc(&mut self, indent: &str, lines: &[String]) {
        for l in lines {
            if l.is_empty() {
                let _ = writeln!(self.buf, "{indent}///");
            } else {
                let _ = writeln!(self.buf, "{indent}/// {l}");
            }
        }
    }

    fn path(&self, p: &TypePath) -> String {
        if p.module == self.module {
            p.name.clone()
        } else {
            format!("crate::{}::{}", p.module, p.name)
        }
    }

    fn value(&self, v: &ValueType) -> String {
        match v {
            ValueType::Builtin(b) => b.rust().to_owned(),
            ValueType::Named(p) => self.path(p),
        }
    }

    fn elem_ty(&self, e: &ElemInfo) -> String {
        match &e.ty {
            ElemType::Complex(p) => self.path(p),
            ElemType::Simple(v) => self.value(v),
            ElemType::Raw => "RawElement".into(),
        }
    }
}

fn lit(s: &str) -> String {
    format!("{s:?}")
}

fn emit_module(m: &Module) -> String {
    let mut o = Out {
        buf: String::new(),
        module: m.name.clone(),
    };
    o.line("// @generated by openxml-codegen from the ECMA-376 Transitional schemas. Do not edit.");
    let _ = writeln!(o.buf, "//! Schema `{}`, target namespace `{}`.", m.file, m.ns_uri);
    o.line("//!");
    let _ = writeln!(
        o.buf,
        "//! Contains {} simple types, {} complex types, {} choice enums and {} global elements.",
        m.simple_types.len(),
        m.complex_types.len(),
        m.enums.len(),
        m.globals.len()
    );
    o.line(
        "#![allow(non_camel_case_types, unused_imports, unused_mut, unused_variables, unused_assignments)]",
    );
    o.line("#![allow(clippy::all, clippy::pedantic)]");
    o.line("");
    o.line("use crate::prelude::*;");
    o.line("");
    for s in &m.simple_types {
        emit_simple(&mut o, s);
    }
    for c in &m.complex_types {
        emit_complex(&mut o, m, c);
    }
    for e in &m.enums {
        emit_enum(&mut o, e);
    }
    if !m.globals.is_empty() {
        o.line("/// Global elements of this schema. Each can be the root of a document part.");
        o.line("pub mod elements {");
        o.line("    use super::*;");
        for g in &m.globals {
            o.line("");
            o.doc("    ", &g.doc);
            let nss: Vec<String> = g.namespaces.iter().map(|n| format!("Ns::{n}")).collect();
            let _ = writeln!(
                o.buf,
                "    pub const {}: ElementDef<{}> = ElementDef::new(Ns::{}, {}, &[{}]);",
                g.const_name,
                if g.ty.module == m.name {
                    g.ty.name.clone()
                } else {
                    format!("crate::{}::{}", g.ty.module, g.ty.name)
                },
                m.ns,
                lit(&g.local),
                nss.join(", ")
            );
        }
        o.line("}");
    }
    o.buf
}

// ----- simple types --------------------------------------------------------------

fn emit_simple(o: &mut Out, s: &SimpleDef) {
    o.doc("", &s.doc);
    match &s.kind {
        SimpleKind::Alias(v) => {
            let _ = writeln!(o.buf, "pub type {} = {};", s.name, o.value(v));
        }
        SimpleKind::List(v) => {
            let _ = writeln!(o.buf, "pub type {} = XmlList<{}>;", s.name, o.value(v));
        }
        SimpleKind::Enum(values) => {
            o.line("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]");
            let _ = writeln!(o.buf, "pub enum {} {{", s.name);
            for (i, v) in values.iter().enumerate() {
                let doc = match &v.doc {
                    Some(d) => format!("`{}`: {d}", doc_text(&v.value)),
                    None => format!("`{}`", doc_text(&v.value)),
                };
                let _ = writeln!(o.buf, "    /// {doc}");
                if i == 0 {
                    o.line("    #[default]");
                }
                let _ = writeln!(o.buf, "    {},", v.variant);
            }
            o.line("}");
            let _ = writeln!(o.buf, "impl {} {{", s.name);
            o.line("    /// All values in schema order.");
            let all: Vec<String> = values.iter().map(|v| format!("Self::{}", v.variant)).collect();
            let _ = writeln!(
                o.buf,
                "    pub const ALL: &'static [Self] = &[{}];",
                all.join(", ")
            );
            o.line("    /// The lexical (XML) form of the value.");
            o.line("    pub fn as_str(self) -> &'static str {");
            o.line("        match self {");
            for v in values {
                let _ = writeln!(o.buf, "            Self::{} => {},", v.variant, lit(&v.value));
            }
            o.line("        }");
            o.line("    }");
            o.line("}");
            let _ = writeln!(o.buf, "impl XmlValue for {} {{", s.name);
            o.line("    fn parse_xml(s: &str) -> Option<Self> {");
            o.line("        Some(match s.trim() {");
            for v in values {
                let _ = writeln!(o.buf, "            {} => Self::{},", lit(&v.value), v.variant);
            }
            o.line("            _ => return None,");
            o.line("        })");
            o.line("    }");
            o.line("    fn write_xml(&self, out: &mut String) {");
            o.line("        out.push_str(self.as_str());");
            o.line("    }");
            o.line("}");
            let _ = writeln!(o.buf, "impl std::fmt::Display for {} {{", s.name);
            o.line("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
            o.line("        f.write_str(self.as_str())");
            o.line("    }");
            o.line("}");
        }
        SimpleKind::Union(members) => {
            o.line("#[derive(Clone, Debug, PartialEq)]");
            let _ = writeln!(o.buf, "pub enum {} {{", s.name);
            for mbr in members {
                let _ = writeln!(o.buf, "    /// Value of member type `{}`.", o.value(&mbr.ty));
                let _ = writeln!(o.buf, "    {}({}),", mbr.variant, o.value(&mbr.ty));
            }
            o.line("}");
            let _ = writeln!(o.buf, "impl Default for {} {{", s.name);
            let _ = writeln!(
                o.buf,
                "    fn default() -> Self {{ Self::{}(Default::default()) }}",
                members[0].variant
            );
            o.line("}");
            let _ = writeln!(o.buf, "impl XmlValue for {} {{", s.name);
            o.line("    fn parse_xml(s: &str) -> Option<Self> {");
            // Members that accept arbitrary text are tried last.
            let ordered = members
                .iter()
                .filter(|m| !m.stringy)
                .chain(members.iter().filter(|m| m.stringy));
            for mbr in ordered {
                let _ = writeln!(
                    o.buf,
                    "        if let Some(v) = <{} as XmlValue>::parse_xml(s) {{ return Some(Self::{}(v)); }}",
                    o.value(&mbr.ty),
                    mbr.variant
                );
            }
            o.line("        None");
            o.line("    }");
            o.line("    fn write_xml(&self, out: &mut String) {");
            o.line("        match self {");
            for mbr in members {
                let _ = writeln!(o.buf, "            Self::{}(v) => v.write_xml(out),", mbr.variant);
            }
            o.line("        }");
            o.line("    }");
            o.line("}");
        }
    }
    o.line("");
}

// ----- complex types ---------------------------------------------------------------

fn field_type(o: &Out, f: &Field) -> String {
    match &f.kind {
        FieldKind::Element { elem, multi } => {
            let t = o.elem_ty(elem);
            match (&elem.ty, multi) {
                (_, true) => format!("Vec<{t}>"),
                (ElemType::Complex(_), false) => format!("Option<Box<{t}>>"),
                (_, false) => format!("Option<{t}>"),
            }
        }
        FieldKind::Choice { path, multi, .. } => {
            if *multi {
                format!("Vec<{}>", o.path(path))
            } else {
                format!("Option<{}>", o.path(path))
            }
        }
        FieldKind::Any { multi, .. } => {
            if *multi {
                "Vec<RawElement>".into()
            } else {
                "Option<RawElement>".into()
            }
        }
    }
}

fn any_test(ns: &AnyNs) -> String {
    match ns {
        AnyNs::Any => "true".into(),
        AnyNs::Other(target) => format!("(child.ns() != Ns::{target} && child.ns() != Ns::NONE)"),
        AnyNs::List { known, uris } => {
            let mut parts = Vec::new();
            if !known.is_empty() {
                let pats: Vec<String> = known.iter().map(|k| format!("Ns::{k}")).collect();
                parts.push(format!("matches!(child.ns(), {})", pats.join(" | ")));
            }
            for u in uris {
                parts.push(format!("child.uri() == {}", lit(u)));
            }
            if parts.is_empty() {
                "false".into()
            } else {
                format!("({})", parts.join(" || "))
            }
        }
    }
}

/// Code that stores `child` into field `i` and advances `pos`.
fn field_handler(o: &Out, fields: &[Field], i: usize) -> String {
    let f = &fields[i];
    let name = &f.name;
    let next = i + 1;
    let extra = "rt::push_extra(&mut this.extra_children, pos, RawElement::read(r, &child)?)";
    let body = match &f.kind {
        FieldKind::Element { elem, multi: false } => match &elem.ty {
            ElemType::Complex(_) => format!(
                "if this.{name}.is_none() {{ this.{name} = Some(Box::new(XmlRead::read_xml(r, &child)?)); }} else {{ {extra}; }}"
            ),
            ElemType::Simple(_) => format!(
                "if this.{name}.is_none() {{ match rt::read_simple(r, &child)? {{ Ok(v) => this.{name} = Some(v), Err(raw) => rt::push_extra(&mut this.extra_children, pos, raw) }} }} else {{ {extra}; }}"
            ),
            ElemType::Raw => format!(
                "if this.{name}.is_none() {{ this.{name} = Some(RawElement::read(r, &child)?); }} else {{ {extra}; }}"
            ),
        },
        FieldKind::Element { elem, multi: true } => match &elem.ty {
            ElemType::Complex(_) => format!("this.{name}.push(XmlRead::read_xml(r, &child)?);"),
            ElemType::Simple(_) => format!(
                "match rt::read_simple(r, &child)? {{ Ok(v) => this.{name}.push(v), Err(raw) => rt::push_extra_at(&mut this.extra_children, {i}, this.{name}.len(), raw) }}"
            ),
            ElemType::Raw => format!("this.{name}.push(RawElement::read(r, &child)?);"),
        },
        FieldKind::Choice {
            path, multi: false, ..
        } => format!(
            "if this.{name}.is_none() {{ this.{name} = Some({}::read_choice(r, &child)?); }} else {{ {extra}; }}",
            o.path(path)
        ),
        FieldKind::Choice {
            path, multi: true, ..
        } => {
            format!("this.{name}.push({}::read_choice(r, &child)?);", o.path(path))
        }
        FieldKind::Any { .. } => unreachable!("wildcards are dispatched separately"),
    };
    format!("{body} pos = {next};")
}

fn emit_complex(o: &mut Out, m: &Module, c: &ComplexDef) {
    let _ = m;
    o.doc("", &c.doc);
    o.line("#[derive(Clone, Debug, Default, PartialEq)]");
    let _ = writeln!(o.buf, "pub struct {} {{", c.name);
    if let ContentDef::Simple(v) = &c.content {
        o.line("    /// The element's text content.");
        let _ = writeln!(o.buf, "    pub value: {},", o.value(v));
    }
    for a in &c.attrs {
        if let Some(d) = &a.doc {
            let _ = writeln!(o.buf, "    /// {d}");
        }
        let _ = writeln!(o.buf, "    pub {}: Option<{}>,", a.field, o.value(&a.ty));
    }
    match &c.content {
        ContentDef::Fields(fields) => {
            for f in fields {
                if let Some(d) = &f.doc {
                    let _ = writeln!(o.buf, "    /// {d}");
                }
                let _ = writeln!(o.buf, "    pub {}: {},", f.name, field_type(o, f));
            }
        }
        ContentDef::Mixed => {
            o.line("    /// Mixed content (text and elements), kept as raw XML.");
            o.line("    pub children: Vec<RawNode>,");
        }
        _ => {}
    }
    o.line("    /// Attributes not described by the schema, including namespace declarations.");
    o.line("    pub extra_attrs: Vec<RawAttribute>,");
    if !matches!(c.content, ContentDef::Simple(_) | ContentDef::Mixed) {
        o.line("    /// Child elements not described by the schema, with their positions.");
        o.line("    pub extra_children: Vec<ExtraChild>,");
    }
    o.line("}");
    o.line("");
    emit_read(o, c);
    emit_write(o, c);
}

fn emit_read(o: &mut Out, c: &ComplexDef) {
    let _ = writeln!(o.buf, "impl XmlRead for {} {{", c.name);
    o.line("    fn read_xml(r: &mut XmlReader<'_>, tag: &StartTag<'_>) -> Result<Self> {");
    o.line("        let mut this = Self::default();");
    o.line("        for a in tag.attributes() {");
    if !c.attrs.is_empty() {
        o.line("            match (a.ns, a.local) {");
        for a in &c.attrs {
            let _ = writeln!(
                o.buf,
                "                (Ns::{}, {}) => if let Some(v) = XmlValue::parse_xml(&a.value) {{ this.{} = Some(v); continue; }},",
                a.ns,
                lit(&a.local),
                a.field
            );
        }
        o.line("                _ => {}");
        o.line("            }");
    }
    o.line("            this.extra_attrs.push(a.to_raw());");
    o.line("        }");
    match &c.content {
        ContentDef::Simple(_) => {
            o.line("        let text = r.read_text(tag)?;");
            o.line("        match XmlValue::parse_xml(&text) {");
            o.line("            Some(v) => this.value = v,");
            o.line("            None => return Err(Error::InvalidValue { name: tag.clark_name(), value: text.into_owned() }),");
            o.line("        }");
        }
        ContentDef::Mixed => {
            o.line("        if !tag.is_empty() {");
            o.line("            loop {");
            o.line("                match r.next_event()? {");
            o.line("                    Event::Start(child) => this.children.push(RawNode::Element(RawElement::read(r, &child)?)),");
            o.line(
                "                    Event::Text(t) => this.children.push(RawNode::Text(t.into_owned())),",
            );
            o.line("                    Event::End => break,");
            o.line("                    Event::Eof => return Err(Error::UnexpectedEof),");
            o.line("                }");
            o.line("            }");
            o.line("        }");
        }
        ContentDef::Empty => {
            o.line("        if !tag.is_empty() {");
            o.line("            while let Some(child) = r.next_child()? {");
            o.line("                let raw = RawElement::read(r, &child)?;");
            o.line("                rt::push_extra(&mut this.extra_children, 0, raw);");
            o.line("            }");
            o.line("        }");
        }
        ContentDef::Fields(fields) => emit_read_fields(o, fields),
    }
    o.line("        Ok(this)");
    o.line("    }");
    o.line("}");
    o.line("");
}

fn emit_read_fields(o: &mut Out, fields: &[Field]) {
    // (ns, local) -> fields accepting that element, in order.
    let mut dispatch: BTreeMap<(String, String), Vec<usize>> = BTreeMap::new();
    let mut key_order: Vec<(String, String)> = Vec::new();
    for (i, f) in fields.iter().enumerate() {
        let elems: Vec<&ElemInfo> = match &f.kind {
            FieldKind::Element { elem, .. } => vec![elem],
            FieldKind::Choice { elems, .. } => elems.iter().collect(),
            FieldKind::Any { .. } => vec![],
        };
        for e in elems {
            let key = (e.ns.clone(), e.local.clone());
            let entry = dispatch.entry(key.clone()).or_default();
            if entry.is_empty() {
                key_order.push(key);
            }
            if !entry.contains(&i) {
                entry.push(i);
            }
        }
    }
    o.line("        if !tag.is_empty() {");
    o.line("            let mut pos: u16 = 0;");
    o.line("            while let Some(child) = r.next_child()? {");
    o.line("                match (child.ns(), child.local()) {");
    // Arms for elements that belong to exactly one field, grouped per field.
    for (i, _) in fields.iter().enumerate() {
        let pats: Vec<String> = key_order
            .iter()
            .filter(|k| dispatch[*k] == [i])
            .map(|(ns, local)| format!("(Ns::{ns}, {})", lit(local)))
            .collect();
        if pats.is_empty() {
            continue;
        }
        let _ = writeln!(
            o.buf,
            "                    {} => {{ {} }}",
            pats.join(" | "),
            field_handler(o, fields, i)
        );
    }
    // Arms for elements that several fields accept: pick by position.
    for key in &key_order {
        let cands = &dispatch[key];
        if cands.len() < 2 {
            continue;
        }
        let mut code = String::new();
        for (n, &i) in cands.iter().enumerate() {
            let handler = field_handler(o, fields, i);
            if n + 1 == cands.len() {
                let _ = write!(code, "{{ {handler} }}");
            } else {
                let _ = write!(code, "if pos <= {} {{ {handler} }} else ", i + 1);
            }
        }
        let _ = writeln!(
            o.buf,
            "                    (Ns::{}, {}) => {code}",
            key.0,
            lit(&key.1)
        );
    }
    // Unknown elements: wildcards, the current choice field, or extra children.
    o.line("                    _ => {");
    let mut chain = String::new();
    for (i, f) in fields.iter().enumerate() {
        let (test, store) = match &f.kind {
            FieldKind::Any { ns, multi } => {
                let store = if *multi {
                    format!("this.{}.push(RawElement::read(r, &child)?);", f.name)
                } else {
                    format!("this.{} = Some(RawElement::read(r, &child)?);", f.name)
                };
                let cond = if *multi {
                    format!("pos <= {} && {}", i + 1, any_test(ns))
                } else {
                    format!(
                        "pos <= {} && this.{}.is_none() && {}",
                        i + 1,
                        f.name,
                        any_test(ns)
                    )
                };
                (cond, store)
            }
            FieldKind::Choice {
                path,
                any: Some(ns),
                multi: true,
                ..
            } => (
                format!("pos <= {} && {}", i + 1, any_test(ns)),
                format!(
                    "this.{}.push({}::Other(RawElement::read(r, &child)?));",
                    f.name,
                    o.path(path)
                ),
            ),
            _ => continue,
        };
        let _ = write!(chain, "if {test} {{ {store} pos = {}; }} else ", i + 1);
    }
    // An unknown element right after a repeating field stays next to its items:
    // inside a repeating choice as `Other`, or anchored to the item position.
    let mut arms = String::new();
    for (i, f) in fields.iter().enumerate() {
        match &f.kind {
            FieldKind::Choice {
                path, multi: true, ..
            } => {
                let _ = write!(
                    arms,
                    "{} => this.{}.push({}::Other(RawElement::read(r, &child)?)), ",
                    i + 1,
                    f.name,
                    o.path(path)
                );
            }
            FieldKind::Element { multi: true, .. } => {
                let _ = write!(
                    arms,
                    "{} => rt::push_extra_at(&mut this.extra_children, {i}, this.{}.len(), RawElement::read(r, &child)?), ",
                    i + 1,
                    f.name
                );
            }
            _ => {}
        }
    }
    if arms.is_empty() {
        let _ = write!(
            chain,
            "{{ rt::push_extra(&mut this.extra_children, pos, RawElement::read(r, &child)?); }}"
        );
    } else {
        let _ = write!(
            chain,
            "{{ match pos {{ {arms}_ => rt::push_extra(&mut this.extra_children, pos, RawElement::read(r, &child)?), }} }}"
        );
    }
    let _ = writeln!(o.buf, "                        {chain}");
    o.line("                    }");
    o.line("                }");
    o.line("            }");
    o.line("        }");
}

fn emit_write(o: &mut Out, c: &ComplexDef) {
    let _ = writeln!(o.buf, "impl XmlWrite for {} {{", c.name);
    o.line("    fn write_xml(&self, w: &mut XmlWriter, ns: Ns, local: &str) {");
    o.line("        w.start_with(ns, local, &self.extra_attrs);");
    for a in &c.attrs {
        let _ = writeln!(
            o.buf,
            "        rt::write_attr(w, Ns::{}, {}, &self.{});",
            a.ns,
            lit(&a.local),
            a.field
        );
    }
    o.line("        w.attrs_raw(&self.extra_attrs);");
    match &c.content {
        ContentDef::Simple(_) => o.line("        w.text_value(&self.value);"),
        ContentDef::Mixed => {
            o.line("        for c in &self.children {");
            o.line("            match c {");
            o.line("                RawNode::Element(e) => e.write(w),");
            o.line("                RawNode::Text(t) => w.text(t),");
            o.line("            }");
            o.line("        }");
        }
        ContentDef::Empty => o.line("        rt::write_extras(w, &self.extra_children, 0);"),
        ContentDef::Fields(fields) => {
            for (i, f) in fields.iter().enumerate() {
                if !matches!(f.kind, FieldKind::Element { multi: true, .. }) {
                    let _ = writeln!(o.buf, "        rt::write_extras(w, &self.extra_children, {i});");
                }
                let name = &f.name;
                match &f.kind {
                    FieldKind::Element { elem, multi } => {
                        let call = match &elem.ty {
                            ElemType::Simple(_) => {
                                format!("rt::write_simple(w, Ns::{}, {}, v)", elem.ns, lit(&elem.local))
                            }
                            _ => format!("v.write_xml(w, Ns::{}, {})", elem.ns, lit(&elem.local)),
                        };
                        if *multi {
                            let _ = writeln!(
                                o.buf,
                                "        for (k, v) in self.{name}.iter().enumerate() {{ rt::write_extras_at(w, &self.extra_children, {i}, k); {call}; }}"
                            );
                            let _ = writeln!(
                                o.buf,
                                "        rt::write_extras_after(w, &self.extra_children, {i}, self.{name}.len());"
                            );
                        } else {
                            let _ = writeln!(o.buf, "        if let Some(v) = &self.{name} {{ {call}; }}");
                        }
                    }
                    FieldKind::Choice { multi, .. } => {
                        if *multi {
                            let _ = writeln!(o.buf, "        for v in &self.{name} {{ v.write_choice(w); }}");
                        } else {
                            let _ = writeln!(
                                o.buf,
                                "        if let Some(v) = &self.{name} {{ v.write_choice(w); }}"
                            );
                        }
                    }
                    FieldKind::Any { multi, .. } => {
                        if *multi {
                            let _ = writeln!(o.buf, "        for v in &self.{name} {{ v.write(w); }}");
                        } else {
                            let _ =
                                writeln!(o.buf, "        if let Some(v) = &self.{name} {{ v.write(w); }}");
                        }
                    }
                }
            }
            let _ = writeln!(
                o.buf,
                "        rt::write_extras(w, &self.extra_children, {});",
                fields.len()
            );
        }
    }
    o.line("        w.end();");
    o.line("    }");
    o.line("}");
    o.line("");
}

// ----- choice enums --------------------------------------------------------------

fn emit_enum(o: &mut Out, e: &ChoiceEnum) {
    o.doc("", &e.doc);
    o.line("#[derive(Clone, Debug, PartialEq)]");
    let _ = writeln!(o.buf, "pub enum {} {{", e.name);
    for v in &e.variants {
        if let Some(d) = &v.doc {
            let _ = writeln!(o.buf, "    /// {d}");
        }
        let ty = o.elem_ty(&v.elem);
        match &v.elem.ty {
            ElemType::Complex(_) => {
                let _ = writeln!(o.buf, "    {}(Box<{ty}>),", v.name);
            }
            _ => {
                let _ = writeln!(o.buf, "    {}({ty}),", v.name);
            }
        }
    }
    o.line("    /// An element not described by the schema, kept as raw XML.");
    o.line("    Other(RawElement),");
    o.line("}");
    o.line("");
    let _ = writeln!(o.buf, "impl {} {{", e.name);
    o.line("    /// Reads the variant for the element opened by `tag`.");
    o.line("    pub fn read_choice(r: &mut XmlReader<'_>, tag: &StartTag<'_>) -> Result<Self> {");
    o.line("        Ok(match (tag.ns(), tag.local()) {");
    for v in &e.variants {
        let pat = format!("(Ns::{}, {})", v.elem.ns, lit(&v.elem.local));
        let expr = match &v.elem.ty {
            ElemType::Complex(_) => format!("Self::{}(Box::new(XmlRead::read_xml(r, tag)?))", v.name),
            ElemType::Simple(_) => format!(
                "match rt::read_simple(r, tag)? {{ Ok(v) => Self::{}(v), Err(raw) => Self::Other(raw) }}",
                v.name
            ),
            ElemType::Raw => format!("Self::{}(RawElement::read(r, tag)?)", v.name),
        };
        let _ = writeln!(o.buf, "            {pat} => {expr},");
    }
    o.line("            _ => Self::Other(RawElement::read(r, tag)?),");
    o.line("        })");
    o.line("    }");
    o.line("");
    o.line("    /// Writes the variant as an element.");
    o.line("    pub fn write_choice(&self, w: &mut XmlWriter) {");
    o.line("        match self {");
    for v in &e.variants {
        let call = match &v.elem.ty {
            ElemType::Simple(_) => format!(
                "rt::write_simple(w, Ns::{}, {}, v)",
                v.elem.ns,
                lit(&v.elem.local)
            ),
            _ => format!("v.write_xml(w, Ns::{}, {})", v.elem.ns, lit(&v.elem.local)),
        };
        let _ = writeln!(o.buf, "            Self::{}(v) => {call},", v.name);
    }
    o.line("            Self::Other(v) => v.write(w),");
    o.line("        }");
    o.line("    }");
    o.line("");
    o.line("    /// Namespace and local name of the element this variant represents.");
    o.line("    pub fn element_name(&self) -> (Ns, &str) {");
    o.line("        match self {");
    for v in &e.variants {
        let _ = writeln!(
            o.buf,
            "            Self::{}(_) => (Ns::{}, {}),",
            v.name,
            v.elem.ns,
            lit(&v.elem.local)
        );
    }
    o.line("            Self::Other(v) => (v.name.ns, &v.name.local),");
    o.line("        }");
    o.line("    }");
    o.line("}");
    o.line("");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lower::lower;
    use crate::registry::Registry;
    use crate::spec::SpecIndex;
    use crate::xsd::parse_schema;

    #[test]
    fn emits_expected_shapes() {
        let text = r#"<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            targetNamespace="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            elementFormDefault="qualified" attributeFormDefault="qualified">
          <xsd:simpleType name="ST_Jc"><xsd:restriction base="xsd:string"><xsd:enumeration value="left"/></xsd:restriction></xsd:simpleType>
          <xsd:complexType name="CT_P"><xsd:sequence>
            <xsd:element name="pPr" type="CT_PPr" minOccurs="0"/>
            <xsd:choice minOccurs="0" maxOccurs="unbounded"><xsd:element name="r" type="CT_PPr"/><xsd:element name="t" type="xsd:string"/></xsd:choice>
            <xsd:element name="r" type="CT_PPr" minOccurs="0"/>
          </xsd:sequence><xsd:attribute name="jc" type="ST_Jc"/></xsd:complexType>
          <xsd:complexType name="CT_PPr"/>
          <xsd:element name="p" type="CT_P"/>
        </xsd:schema>"#;
        let reg = Registry::new(vec![parse_schema("wml.xsd", text).unwrap()]);
        let krate = lower(&reg, &SpecIndex::empty());
        let files = emit_crate(&krate);
        assert_eq!(files[0].0, "mod.rs");
        assert!(files[0].1.contains("pub mod wml;"));
        let src = &files[1].1;
        assert!(src.contains("pub enum ST_Jc {"), "{src}");
        assert!(src.contains("pub p_pr: Option<Box<CT_PPr>>,"));
        assert!(src.contains("pub choice: Vec<CT_P_Choice>,"));
        assert!(src.contains("pub r: Option<Box<CT_PPr>>,"));
        assert!(src.contains("pub jc: Option<ST_Jc>,"));
        assert!(
            src.contains("(Ns::W, \"r\") => if pos <= 2 {"),
            "position-dependent dispatch:\n{src}"
        );
        assert!(src.contains("pub const P: ElementDef<CT_P> = ElementDef::new(Ns::W, \"p\", &[Ns::W]);"));
        assert!(src.contains("Other(RawElement),"));
    }
}
