<?xml version="1.0" encoding="UTF-8"?>
<!-- Minimal schema for the XML namespace (xml:lang, xml:space, xml:base, xml:id),
     equivalent to the W3C "xml.xsd", used only to let validators resolve the
     xml:* attribute references of the ECMA-376 schemas offline. -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.w3.org/XML/1998/namespace" xml:lang="en">
  <xsd:attribute name="lang">
    <xsd:simpleType>
      <xsd:union memberTypes="xsd:language">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string"><xsd:enumeration value=""/></xsd:restriction>
        </xsd:simpleType>
      </xsd:union>
    </xsd:simpleType>
  </xsd:attribute>
  <xsd:attribute name="space">
    <xsd:simpleType>
      <xsd:restriction base="xsd:NCName">
        <xsd:enumeration value="default"/>
        <xsd:enumeration value="preserve"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>
  <xsd:attribute name="base" type="xsd:anyURI"/>
  <xsd:attribute name="id" type="xsd:ID"/>
</xsd:schema>
